### ISSUE TITLE
HWIOAuthBundle: Call to undefined method HWI\...\Token\OAuthToken::getProviderKey() 

### ISSUE THREAD

**Issue by CoteViande** [FriendsOfSymfony/FOSUserBundle#1952]
Since [this commit and change of the registration controller](https://github.com/FriendsOfSymfony/FOSUserBundle/commit/3b65b9f6b48c339b2776fe2c9e3c21c030eaf1a8), I get this error when registrating with facebook using HWIOAuthBundle: 

`Error: Call to undefined method HWI\Bundle\OAuthBundle\Security\Core\Authentication\Token\OAuthToken::getProviderKey() in C:\wamp\www\Symfony\vendor\friendsofsymfony\user-bundle\Controller\RegistrationController.php line 156`

For now, I intend to install a previous version of FOSUB. But I'd also like to stay up to date. 
Is there any way I can fix this?

**Comment by stof** [comment]
I will work on a fix in the next few days. I have an idea to fix it

**Comment by CoteViande** [comment]
Did you find some time to work it out?

**Comment by XWB** [comment]
I believe this was resolved, the method `getTargetUrlFromSession()` does not exist anymore.

**Comment by IndraGunawan** [comment]
i still face this issue with this package version
`
hwi/oauth-bundle                     0.5.3
friendsofsymfony/user-bundle         v2.0.1
`

**Comment by tomilsinszki** [comment]
This bug still exists.

The method `getTargetUrlFromSession()` still exists, please see here: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/RegistrationController.php#L181

FYI - I only get this error if I log in with Facebook using HWIOAuthBundle and then visit the registration confirmation page.
