### ISSUE TITLE
Attempted to call an undefined method named "getUnifOfWork" of class "Doctrine\ORM\EntityManager"

### ISSUE THREAD

**Issue by xDaizu** [FriendsOfSymfony/FOSUserBundle#2053]
I keep getting
```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "getUnifOfWork" of class "Doctrine\ORM\EntityManager". Did you mean to call "getUnitOfWork"?" at /home/domain/public_html/vendor/friendsofsymfony/user-bundle/Doctrine/UserListener.php line 111 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\UndefinedMethodException(code: 0): Attempted to call an undefined method named \"getUnifOfWork\" of class \"Doctrine\\ORM\\EntityManager\".\nDid you mean to call \"getUnitOfWork\"? at /home/domain/public_html/vendor/friendsofsymfony/user-bundle/Doctrine/UserListener.php:111)"} []
```
in the production environment after login when it goes to domain/login_check. After that if I enter manuall other router it loads smoothly (so the user is correctly logged)

**Comment by xDaizu** [comment]
It's weird because navigating the last pull requests I found out this seems to be fixed... but I executed a composer update today and I still get it... am I missing something? :confused:

**Comment by stloyd** [comment]
This was already fixed by #2049.

**Comment by xDaizu** [comment]
@stloyd Hmmm... I know, that's what I said in my comment. But I still get the error, so... something is not updated... or I'm updating it wron... nevermind, as I wrote this comment it finally updated. It took 3 consecutives executions of composer update. That's weird.
