### ISSUE TITLE
Overriding templates in a child bundle is broken after ed6a1a9

### ISSUE THREAD

**Issue by Gemorroj** [FriendsOfSymfony/FOSUserBundle#2378]
After commit ed6a1a931b438da361eb76f5145a9c25616cb0ca I can't use my templates.
AppKernel.php
```php
    public function registerBundles()
    {
        $bundles = [
            ...
            new FOS\UserBundle\FOSUserBundle(),
            new Wapinet\UserBundle\WapinetUserBundle(),
        ];
        return $bundles;
    }
```

Wapinet\UserBundle\WapinetUserBundle.php
```php
<?php

namespace Wapinet\UserBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class WapinetUserBundle extends Bundle
{
    public function getParent()
    {
        return 'FOSUserBundle';
    }
}
```

and i override some controllers and templates.
after this update symfony use `FOS\UserBundle\FOSUserBundle`, not my overrided code (`Wapinet\UserBundle\WapinetUserBundle`).

**Comment by mvrhov** [comment]
Did you try overwriting them with the new syntax. Not the old one?

**Comment by Gemorroj** [comment]
Yes, this is also an option. but then I'd have to rewrite **everything**!
Every method that calls `render`. Every template that uses a different template FOSUserBundle.

**Comment by mvrhov** [comment]
Two points.: 
* 2.0 is not yet stable so BC are allowed.
* it's not that many templates

**Comment by Tomsgu** [comment]
Duplication of issue #2376 .

**Comment by xabbuh** [comment]
@Gemorroj Can you please check if symfony/symfony#21077 would solve your issue?

**Comment by stof** [comment]
The template override issue is because of a bug in Symfony (discovered when we did this change). Fixing it is in progress on the Symfony side and should be available in the next patch releases. In the meantime, you can keep using the beta1 release (as the change was done after the release).

I will keep this ticket open until the issue is solved on the Symfony side.

**Comment by stof** [comment]
For reference, the Symfony PR is at https://github.com/symfony/symfony/pull/19586

**Comment by homersimpsons** [comment]
This has been fixed: https://github.com/symfony/symfony/commit/0c77ce2355dad4d5011421b88755f2c6e430ef0f
I don't know when new release with this fix will be released

**Comment by homersimpsons** [comment]
Well, @stof you can close, fix have been pushed :)

**Comment by peterrehm** [comment]
Hrm, I am still seeing issues using the LiipThemeBundle the overriden template is not working. It works on `dev-master#c0ba632`.

**Comment by Gemorroj** [comment]
After updating Symfony 3.2.2 works well.

**Comment by peterrehm** [comment]
Actually after some research I think my issue is related to the LiipThemeBundle.

**Comment by Jean85** [comment]
The related Symfony PR has been merged and released, I was able to fix this upgrading to the latest patch version.

**Comment by XWB** [comment]
:+1:
